### ISSUE TITLE
Scripts Function

### ISSUE THREAD

**Issue by arivmarsal** [khalisafkari/Blogger-video-downloader#3]
Hi..
This scripts can redirect  blogger.com/video-play.mp4?contentId= 
to blogger.com/video.g?token=?

**Comment by khalisafkari** [comment]
to take an old video on blogger.com/video-play.mp4?contentId= url
no longer possible because Google has removed the function

but you can see my latest repo [khalis] (https://github.com/khalisafkari/khalis)

which on my latest version you only need to enter the url https://khalis-khalis411.now.sh/?url=https://prikate09.blogspot.com/2017/10/all-ani-29-oktober-2017-413.html

and all the videos on the blog page will be taken

## Please provide PR if the code is useful for you
